name: 'dbt_learning'
version: '1.0'
config-version: 2

profile: 'dbt_learning'

model-paths: ["models"]
target-path: "target"
analysis-paths: ["analysis"]
test-paths: ["tests"]

models:
  dbt_learning:

    staging:
      carrefour:
        +target: us
        +schema: carrefour_start
        +materialized: view

      jaffle_shop:
        +target: eu
        +schema: dbt_learning
        +materialized: view

    mart:
      carrefour:
        +target: us
        +schema: carrefour_start
        +materialized: table

      jaffle_shop:
        +target: eu
        +schema: dbt_learning
        +materialized: table
