sources:
  - name: carrefour
    schema: carrefour_start
    tables:
      - name: crf_hyp_sales_fr_data
        columns:
          - name: CA
            tests:
              - dbt_utils.accepted_range:
                  min_value: 0
      - name: crf_prx_sales_fr_data
        columns:
          - name: CA
            tests:
              - dbt_utils.accepted_range:
                  min_value: 0
      - name: crf_sup_sales_fr_data
        columns:
          - name: CA
            tests:
              - dbt_utils.accepted_range:
                  min_value: 0
