sources:
  - name: carrefour
    schema: carrefour_start
    tables:
      - name: crf_hyp_sales_fr_data
      - name: crf_prx_sales_fr_data
      - name: crf_sup_sales_fr_data
      - name: ferrero_sales_per_week_dirty
