version: 2

sources:
  - name: raw
    # database: biq-query-artefact   # le project_id BigQuery réel
    schema: dbt_learning          # le dataset BigQuery contenant tes tables
    tables:
      - name: raw_customers
        description: Table des clients
        columns:
          - name: id
            description: primary key
            tests:
              - unique
              - not_null

      - name: orders
        description: Table des commandes
        columns:
          - name: id
            data_tests:
              - unique
              - not_null
          - name: status
            description: "{{ doc('order_status') }}"
            data_tests:
              - accepted_values:
                  arguments:
                    values: ['placed', 'shipped', 'completed', 'returned', 'return_pending']
          - name: user_id
            data_tests:
              - relationships:
                  arguments:
                    to: ref('stg_jaffle_shop__customers')
                    field: customer_id
            freshness:
              warn_after:
                count: 12
                period: hour
              error_after:
                count: 1
                period: day
            loaded_at_field: _etl_loaded_at
