sources:
  - name: raw      # <-- ce nom est utilisé dans dbt
    # database: biq-query-artefact
    schema: dbt_learning
    tables:
      - name: raw_payments
        config:
          loaded_at_field: _batched_at
          freshness:
            warn_after: {count: 12, period: hour}
            error_after: {count: 24, period: hour}